<a href="https://colab.research.google.com/github/RakeshBB08/MachineLearning/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PREPROCESSING

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
# Data Preprocessing
# importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
# label encoding for Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Building The ANN

In [ ]:
# Initialising the ANN
ann = tf.keras.models.Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [ ]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 1,activation = "sigmoid"))

#Training the ANN

In [ ]:
# Compiling the ANN
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
# Training the ANN
ann.fit(X_train, y_train, batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7418 - accuracy: 0.5389
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5153 - accuracy: 0.7908
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4498 - accuracy: 0.8099
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4291 - accuracy: 0.8160
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4193 - accuracy: 0.8185
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8217
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8242
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4005 - accuracy: 0.8266
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3946 - accuracy: 0.8305
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3887 - accura

#Predicting the RESULT

for the customer:


*   geo= france
*   credit score = 600
*   gender = male
*   Age = 40 years
*   Tenure = 3 years
*   Blalance = 60000
*   Number of products = 2
*   credit card? = yes
*   Active mem? = yes
* est salary = 50000



In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 22ms/step
[[False]]


In [21]:
# predicting the test result
y_pred = ann.predict(X_test)>0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1508   87]
 [ 192  213]]
0.8605
